<?php


namespace HuanL\Core\Tests;

use HuanL\Core\Application;
use HuanL\Extend\InsideHttpRequest;
use PHPUnit\Framework\TestCase;

class HuanLHttpTest extends TestCase {

    /**
     * @var InsideHttpRequest
     */
    protected $httpRequest = null;

    protected $dir = '';

    public function setUp()/* The :void return type declaration that should be here would cause a BC issue */ {
        parent::setUp(); // TODO: Change the autogenerated stub
        //启动操作
        $this->httpRequest = new InsideHttpRequest(function () {
            $app = new Application(
                $this->dir
            );
            $app->run();
        });
    }

    public function get($uri, $param = []) {
        $this->httpRequest->get($uri, $param);
        return $this;
    }

    public function post($uri, $param = []) {
        $this->httpRequest->post($uri, $param);
        return $this;
    }

    public function put($uri, $param = []) {
        $this->httpRequest->put($uri, $param);
        return $this;
    }

    public function delete($uri, $param = []) {
        $this->httpRequest->delete($uri, $param);
        return $this;
    }

    public function method($method, $uri, $param = []) {
        $this->httpRequest->method($method, $uri, $param);
        return $this;
    }

    public function domain(string $domain) {
        $this->httpRequest->domain($domain);
        return $this;
    }

    public function data($data) {
        $this->httpRequest->data($data);
        return $data;
    }

    public function request() {
        $this->httpRequest->request();
        return $this;
    }

    public function content() {
        return $this->httpRequest->content();
    }

    public function json() {
        return $this->httpRequest->json();
    }
}